### ISSUE TITLE
use existing webserver

### ISSUE THREAD

**Issue by Lukas1818** [thecodingmachine/workadventure#1135]
I have already have a webserver (caddy2) running on my server, so I can not run the traefik webserver at port 80 and 443. Furthermore I do not like that traefik needs access to the dockersocket.

Can I simple setup 3 reverse tunnel in caddy instead of using traefik?

A other solution should be to disable tls on traefik and tunnel traefik trough caddy. So how can I disable tls in traefik?
But I do not like this solution.

**Comment by moufmouf** [comment]
You can absolutely replace Traefik with something else.
The only thing you need to do is indeed to reverse proxy front and pusher containers.
Also, keep in mind that Traefik is acting as a SSL termination point, so Caddy will have to handle certificates for you.

**Comment by Lukas1818** [comment]
Thanks

Exist any information which port of the image is using inside the container, so I now which port I must tunnel/expose. I had take a look in the Dokerfiles but I have not seen any `EXPOSE` entry. I have also not found any documentation about it.

>The only thing you need to do is indeed to reverse proxy front and pusher containers.

If I do not expose the `back` how does the communtication with it work? Should I put in the same docker-network as the `pusher`, so they can communicate with each other?

>Also, keep in mind that Traefik is acting as a SSL termination point, so Caddy will have to handle certificates for you.

That is no problem. Caddy does use SSL by default. So there is nothing what I need to enable. If you do not want to use SSL you must explicit disable it.

**Comment by moufmouf** [comment]
You can have a look at the Traefik conf in docker-compose.yml labels.

Front: 8080 (in dev) or 80 (in prod)
Pusher: 8080

You don't have to expose the back because the back is talking to pusher only. But indeed, pusher and back must be in the same Docker network.

**Comment by Lukas1818** [comment]
I was able to get workadventure running with caddy.
Here is my configuration, may it useful for someone, how has similar issues.

`docker-compose.yml` (caddy has his own docker-compose)
```yml
version: "3.3"
services:
  front:
    image: thecodingmachine/workadventure-front:master
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: $JITSI_URL
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      PUSHER_URL: //pusher.${DOMAIN}
      TURN_SERVER: "${TURN_SERVER}"
      TURN_USER: "${TURN_USER}"
      TURN_PASSWORD: "${TURN_PASSWORD}"
      START_ROOM_URL: "${START_ROOM_URL}"
    ports:
      - "127.0.0.1:15680:80"
    restart: unless-stopped

  pusher:
    image: thecodingmachine/workadventure-pusher:master
    command: yarn run runprod
    environment:
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      SECRET_KEY: yourSecretKey
      API_URL: back:50051
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    ports:
      - "127.0.0.1:15688:8080"
    networks:
       pusher-back:
       default:
    restart: unless-stopped

  back:
    image: thecodingmachine/workadventure-back:master
    command: yarn run runprod
    environment:
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      ADMIN_API_URL: "$ADMIN_API_URL"
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    networks:
       pusher-back:
    restart: unless-stopped

networks:
  pusher-back:
```
`.env`:
```env
# The base domain
DOMAIN=workadventure.example.com

DEBUG_MODE=false
JITSI_URL=meet.jit.si
# If your Jitsi environment has authentication set up, you MUST set JITSI_PRIVATE_MODE to "true" and you MUST pass a SECRET_JITSI_KEY to generate the JWT secret
JITSI_PRIVATE_MODE=false
JITSI_ISS=
SECRET_JITSI_KEY=

# URL of the TURN server (needed to "punch a hole" through some networks for P2P connections)
TURN_SERVER=
TURN_USER=
TURN_PASSWORD=

# The URL used by default, in the form: "/_/global/map/url.json"
START_ROOM_URL=/_/global/maps.workadventu.re/Floor0/floor0.json

# admin api
ADMIN_API_TOKEN=
ADMIN_API_URL=
```

`Caddyfile`
```json
workadventure.example.com {
        reverse_proxy localhost:15680
}
pusher.workadventure.example.com {
        reverse_proxy localhost:15688 {
}
```


I did bind the ports of workadventure to localhost and reverse proxy them with Caddy. Alternative you can put the Caddy container in the same docker-network as the `pusher` and the `front` containers.
