### ISSUE TITLE
Backend does not connect to IPv6 only redis

### ISSUE THREAD

**Issue by telmich** [thecodingmachine/workadventure#1657]
If you try to deploy workadventure in an IPv6 only kubernetes cluster, the backend fails with this error:

```
Error connecting to Redis: Error: getaddrinfo ENOTFOUND wa1-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'wa1-redis'
}
Error connecting to Redis: Error: getaddrinfo ENOTFOUND wa1-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'wa1-redis'
}
```

Using the following container:

```
        - command:
            - sh
            - -c
            - "yarn install && yarn run runprod"
          env:
            - name: ADMIN_API_TOKEN
            - name: ALLOW_ARTILLERY
              value: "true"
            - name: DEBUG
              value: '*'
            - name: JITSI_ISS
            - name: JITSI_URL
            - name: MAX_PER_GROUP
              value: MAX_PER_GROUP
            - name: NODE_ENV
              value: development
            - name: REDIS_HOST
              value: {{ .Release.Name}}-redis
            - name: SECRET_JITSI_KEY
            - name: SECRET_KEY
              value: yourSecretKey
            - name: STORE_VARIABLES_FOR_LOCAL_MAPS
              value: "true"
            - name: TURN_STATIC_AUTH_SECRET
              value: SomeStaticAuthSecret
          image: thecodingmachine/workadventure-back:v1.6.4
```

However the container *can* resolve and connect to redis:

```
root@wa1-back-5cdf6c477-wpjzn:/usr/src# redis-cli -h wa1-redis
wa1-redis:6379> 
```
