### ISSUE TITLE
Connection lost after about one hour

### ISSUE THREAD

**Issue by mielune** [thecodingmachine/workadventure#1951]
Hi WA community,

I deployed an instance in my docker swarm cluster and it is working fine for about one hour.
After that, every body have a "Connection lost, reconnect..."
No errors or warnings in the browser console, nether in the server side services.
Restarting the pusher solve the issue.
Memory limit set to 4G for pusher and back, 2G for otherones.

Attached the docker swarm docker-compose.yml I used (I have a federated Traefik instance in the cluster).

Using last release v1.8.4.

Thanks for your help.

[docker-compose-env.txt](https://github.com/thecodingmachine/workadventure/files/8213725/docker-compose-env.txt)

**Comment by moufmouf** [comment]
Hi @mielune ,

I must admit I have no idea what is going on. But I see in your docker-compose file that you built it from the "development" docker-file.
If you are doing production work, I'd highly recommend starting from the "contrib/production/docker-compose.yml" file.
It is using the pre-built images that we are using ourselves in production. Maybe that might change a few things?

**Comment by mielune** [comment]
Hi @moufmouf ,

Thank you for your suggestion to use prebuilt images.
I did it today, and still having the issue.
I will look to check and get logs from containers during next days.

PS: I clean the docker-compose, removing redis and messages services, it seems that message service where never used.

**Comment by mielune** [comment]
Hello @moufmouf 

I attached here the docker-compose with the prebuilt images.
I did some cleaning removing services that seems not to be used anymore.

I also replace the OIDC usaged inside WA by an reverse proxy doing it for me.

Do I have a way to enable more debug logs in pusher and back services to help for debug the issue ?

[docker-compose-env.yml.txt](https://github.com/thecodingmachine/workadventure/files/8242804/docker-compose-env.yml.txt)

**Comment by mielune** [comment]
I removed all the OIDC features and enable the disable anonymous too.

After looking inside the logs in the server side, I saw this logs from pusher when a user

```
A user left
at AuthenticateController.getUserByUserIdentifier (/usr/src/dist/src/Controller/AuthenticateController.js:260:46)
at /usr/src/dist/src/Controller/AuthenticateController.js:58:56
openIDCallback => fetchMemberDataByUuid Error: No admin backoffice set!
at AdminApi.fetchMemberDataByUuid (/usr/src/dist/src/Services/AdminApi.js:32:35)
Calling joinRoom
```

I don't understand by the openIDCallback is call by the app.

**Comment by shyoun0303** [comment]
I am also operating through aws' ecs, but after about an hour, CONNECTION LOST is occurring.
Is there any way to solve this problem?

**Comment by moufmouf** [comment]
Weird. I never faced those issues, but the pusher and the back server are on the same physical machine in my setup. Could this be a kind of network timeout between the pusher and the back?
Anythink in the Docker logs?

**Comment by mielune** [comment]
I saw that it is due to a timeout on the network routing mesh of docker swarm that close the open socket after a delay of inactivity.
I solved this by adding this config into the deploy config of the back service:  `endpoint_mode: dnsrr`
Doc here: https://docs.docker.com/network/overlay/#bypass-the-routing-mesh-for-a-swarm-service


```yaml
  back:
    image: thecodingmachine/workadventure-back:$BASE_TAG
    environment:
      - SECRET_JITSI_KEY=
      - SECRET_KEY=secret
      - ADMIN_API_TOKEN=token
      - ADMIN_API_URL=
      - TURN_SERVER=
      - TURN_USER=
      - TURN_PASSWORD=
      - TURN_STATIC_AUTH_SECRET=
      - STUN_SERVER=stun:stun.ippi.fr:3478
      - JITSI_URL=meet.jit.si
      - JITSI_ISS=
      - MAX_PER_GROUP=12
      - STORE_VARIABLES_FOR_LOCAL_MAPS=true
      - ALLOW_ARTILLERY=true
    networks:
      - "default"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
      placement:
        constraints:
        - 'node.role == worker'
      update_config:
        parallelism: 1
        delay: 10s
```
