### ISSUE TITLE
`chat.workadventure.localhost` refused to connect

### ISSUE THREAD

**Issue by SimonBiggs** [thecodingmachine/workadventure#2706]
Thank you so much for making this product source available. I am have a great time spinning it up. I've hosted it over on https://play.gather.guildofentrepreneurs.com/ using the following docker image:

https://github.com/thecodingmachine/workadventure/tree/develop/contrib/docker

I have hit an issue with the chat, I'd be keen for a hand if possible :).

When I go to the webserver and click on "chat" it says "chat.workadventure.localhost" refused to connect. Here is a screenshot, and I'll detail my rough install steps below for context.

![image](https://user-images.githubusercontent.com/6559099/195753848-356f94f4-c290-41f0-b00c-354bc4efbc4e.png)

---

```bash
mkdir git
cd git
git clone https://github.com/thecodingmachine/workadventure.git
cd cd workadventure/contrib/docker/

cp docker-compose.prod.yaml docker-compose.yaml
cp .env.prod.template .env

# Then edit .env (I'll copy in the parts I changed in .env below)
vim .env

docker-compose up -d
```

```yaml
...

#
# Networking
#

# The base domain
DOMAIN=gather.guildofentrepreneurs.com

# Subdomains
# MUST match the DOMAIN variable above
FRONT_HOST=play.gather.guildofentrepreneurs.com
CHAT_HOST=chat.gather.guildofentrepreneurs.com
PUSHER_HOST=pusher.gather.guildofentrepreneurs.com
BACK_HOST=api.gather.guildofentrepreneurs.com
MAP_STORAGE_HOST=map-storage.gather.guildofentrepreneurs.com
MAPS_HOST=maps.gather.guildofentrepreneurs.com
ICON_HOST=icon.gather.guildofentrepreneurs.com
UPLOADER_HOST=uploader.gather.guildofentrepreneurs.com

...
```

I also attempted to make the following change to `/etc/hosts`, but it did not appear to help:

```hosts
127.0.1.1 gather.guildofentrepreneurs.com gather
127.0.0.1 localhost

127.0.0.1 gather.workadventure.localhost
127.0.0.1 play.gather.workadventure.localhost
127.0.0.1 chat.gather.workadventure.localhost
127.0.0.1 pusher.gather.workadventure.localhost
127.0.0.1 api.gather.workadventure.localhost
127.0.0.1 map-storage.gather.workadventure.localhost
127.0.0.1 maps.gather.workadventure.localhost
127.0.0.1 icons.gather.workadventure.localhost
127.0.0.1 uploader.gather.workadventure.localhost

127.0.0.1 gather.guildofentrepreneurs.com
127.0.0.1 play.gather.guildofentrepreneurs.com
127.0.0.1 chat.gather.guildofentrepreneurs.com
127.0.0.1 pusher.gather.guildofentrepreneurs.com
127.0.0.1 api.gather.guildofentrepreneurs.com
127.0.0.1 map-storage.gather.guildofentrepreneurs.com
127.0.0.1 maps.gather.guildofentrepreneurs.com
127.0.0.1 icons.gather.guildofentrepreneurs.com
127.0.0.1 uploader.gather.guildofentrepreneurs.com
```

**Comment by SimonBiggs** [comment]
And, if it helps, here is the docker log:

[docker.log](https://github.com/thecodingmachine/workadventure/files/9782253/docker.log)

**Comment by ieric** [comment]
i fixed this issue by adding `- CHAT_URL=//${CHAT_HOST}` to the environment labels of the front container in the docker-compose.yaml

**Comment by SimonBiggs** [comment]
Yup, when making that change it is now resolved:

![image](https://user-images.githubusercontent.com/6559099/197056792-65ef6963-9f08-4af2-b6fd-b4247048d580.png)

Thank you @ieric :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
Heya @StewardsoftheGuild,

Just a heads up, the chat feature on https://play.gather.guildofentrepreneurs.com/ is now fixed :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
For future readers, for git commit fde4fb54ff84835a797e14321c6594f3229cbf5c of this repository, here's a full copy of my currently working `docker-compose.yaml` that works well:

```yaml
version: "3.6"
services:
  reverse-proxy:
    image: traefik:v2.8
    command:
      - --log.level=${LOG_LEVEL}
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # Entry points
      - --entryPoints.web.address=:${HTTP_PORT}
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:${HTTPS_PORT}
      # HTTP challenge
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      # Let's Encrypt's staging server
      # uncomment during testing to avoid rate limiting
      #- --certificatesresolvers.dnsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/letsencrypt/:/letsencrypt/
    restart: ${RESTART_POLICY}

  front:
    image: thecodingmachine/workadventure-front:${VERSION}
    environment:
      - DEBUG_MODE
      - JITSI_URL
      - JITSI_PRIVATE_MODE
      - ENABLE_FEATURE_MAP_EDITOR
      - PUSHER_URL=//${PUSHER_HOST}
      - ICON_URL=//${ICON_HOST}
      - CHAT_URL=//${CHAT_HOST}   # This is the line that was added
      - TURN_SERVER
      - TURN_USER
      - TURN_PASSWORD
      - TURN_STATIC_AUTH_SECRET
      - STUN_SERVER
      - SKIP_RENDER_OPTIMIZATIONS
      - MAX_PER_GROUP
      - MAX_USERNAME_LENGTH
      - DISABLE_ANONYMOUS
      - DISABLE_NOTIFICATIONS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`${FRONT_HOST}`)"
      - "traefik.http.routers.front.entryPoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.routers.front-ssl.rule=Host(`${FRONT_HOST}`)"
      - "traefik.http.routers.front-ssl.entryPoints=websecure"
      - "traefik.http.routers.front-ssl.service=front"
      - "traefik.http.routers.front-ssl.tls=true"
      - "traefik.http.routers.front-ssl.tls.certresolver=myresolver"
    restart: ${RESTART_POLICY}

  chat:
    image: thecodingmachine/workadventure-chat:${VERSION}
    environment:
      - PUSHER_URL=//${PUSHER_HOST}
      - UPLOADER_URL=//${UPLOADER_HOST}
      - EMBEDLY_KEY=${EMBEDLY_KEY}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`${CHAT_HOST}`)"
      - "traefik.http.routers.chat.entryPoints=web"
      - "traefik.http.services.chat.loadbalancer.server.port=80"
      - "traefik.http.routers.chat-ssl.rule=Host(`${CHAT_HOST}`)"
      - "traefik.http.routers.chat-ssl.entryPoints=websecure"
      - "traefik.http.routers.chat-ssl.service=chat"
      - "traefik.http.routers.chat-ssl.tls=true"
      - "traefik.http.routers.chat-ssl.tls.certresolver=myresolver"
    restart: ${RESTART_POLICY}

  pusher:
    image: thecodingmachine/workadventure-pusher:${VERSION}
    command: yarn run runprod
    environment:
      - SECRET_KEY
      - API_URL
      - FRONT_URL=https://${FRONT_HOST}
      - PUBLIC_MAP_STORAGE_URL=https://${MAP_STORAGE_HOST}
      - DISABLE_ANONYMOUS
      - START_ROOM_URL
      - EJABBERD_DOMAIN=ejabberd
      - OPID_PROMPT=login
      - ENABLE_CHAT
      - ENABLE_CHAT_UPLOAD
      # Only used if you set up a JWT authentication mechanism in Ejabberd
      - EJABBERD_JWT_SECRET
      - EJABBERD_DOMAIN
      - EJABBERD_WS_URI

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pusher.rule=Host(`${PUSHER_HOST}`)"
      - "traefik.http.routers.pusher.entryPoints=web"
      - "traefik.http.services.pusher.loadbalancer.server.port=8080"
      - "traefik.http.routers.pusher-ssl.rule=Host(`${PUSHER_HOST}`)"
      - "traefik.http.routers.pusher-ssl.entryPoints=websecure"
      - "traefik.http.routers.pusher-ssl.service=pusher"
      - "traefik.http.routers.pusher-ssl.tls=true"
      - "traefik.http.routers.pusher-ssl.tls.certresolver=myresolver"
    restart: ${RESTART_POLICY}

  back:
    image: thecodingmachine/workadventure-back:${VERSION}
    command: yarn run runprod
    environment:
      - SECRET_JITSI_KEY
      - ENABLE_FEATURE_MAP_EDITOR
      - SECRET_KEY
      - ADMIN_API_TOKEN
      - ADMIN_API_URL
      - TURN_SERVER
      - TURN_USER
      - TURN_PASSWORD
      - TURN_STATIC_AUTH_SECRET
      - STUN_SERVER
      - JITSI_URL
      - JITSI_ISS
      - BBB_URL
      - BBB_SECRET
      - MAX_PER_GROUP
      - STORE_VARIABLES_FOR_LOCAL_MAPS
      - REDIS_HOST=redis
      - PROMETHEUS_AUTHORIZATION_TOKEN
      - MAP_STORAGE_URL=map-storage:50053
      - PUBLIC_MAP_STORAGE_URL=https://${MAP_STORAGE_HOST}
      - PLAYER_VARIABLES_MAX_TTL
      - EJABBERD_API_URI
      - EJABBERD_DOMAIN
      - ENABLE_CHAT
      - ENABLE_CHAT_UPLOAD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`${BACK_HOST}`)"
      - "traefik.http.routers.back.entryPoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back-ssl.rule=Host(`${BACK_HOST}`)"
      - "traefik.http.routers.back-ssl.entryPoints=websecure"
      - "traefik.http.routers.back-ssl.service=back"
      - "traefik.http.routers.back-ssl.tls=true"
      - "traefik.http.routers.back-ssl.tls.certresolver=myresolver"
    restart: ${RESTART_POLICY}

  uploader:
    image: thecodingmachine/workadventure-uploader:${VERSION}
    environment:
      - UPLOADER_URL=//${UPLOADER_HOST}
      #AWS
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_URL=${AWS_URL}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      #REDIS
      - REDIS_HOST=${UPLOADER_REDIS_HOST}
      - REDIS_PORT=${UPLOADER_REDIS_PORT}
      #CHAT
      - ADMIN_API_URL=${ADMIN_API_URL}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uploader.rule=Host(`${UPLOADER_HOST}`)"
      - "traefik.http.routers.uploader.entryPoints=web"
      - "traefik.http.services.uploader.loadbalancer.server.port=8080"
      - "traefik.http.routers.uploader-ssl.rule=Host(`${UPLOADER_HOST}`)"
      - "traefik.http.routers.uploader-ssl.entryPoints=websecure"
      - "traefik.http.routers.uploader-ssl.service=uploader"
      - "traefik.http.routers.uploader-ssl.tls=true"
      - "traefik.http.routers.uploader-ssl.tls.certresolver=myresolver"

  icon:
    image: matthiasluedtke/iconserver:v3.13.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.icon.rule=Host(`${ICON_HOST}`)"
      - "traefik.http.routers.icon.entryPoints=web"
      - "traefik.http.services.icon.loadbalancer.server.port=8080"
      - "traefik.http.routers.icon-ssl.rule=Host(`${ICON_HOST}`)"
      - "traefik.http.routers.icon-ssl.entryPoints=websecure"
      - "traefik.http.routers.icon-ssl.service=icon"
      - "traefik.http.routers.icon-ssl.tls=true"
      - "traefik.http.routers.icon-ssl.tls.certresolver=myresolver"

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

  ejabberd:
    image: thecodingmachine/workadventure-simple-ecs:${VERSION}

  map-storage:
    image: thecodingmachine/workadventure-map-storage:${VERSION}
    environment:
      PROMETHEUS_AUTHORIZATION_TOKEN: "$PROMETHEUS_AUTHORIZATION_TOKEN"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.map-storage.rule=Host(`${MAP_STORAGE_HOST}`)"
      - "traefik.http.routers.map-storage.entryPoints=web"
      - "traefik.http.services.map-storage.loadbalancer.server.port=3000"
      - "traefik.http.routers.map-storage-ssl.rule=Host(`${MAP_STORAGE_HOST}`)"
      - "traefik.http.routers.map-storage-ssl.entryPoints=websecure"
      - "traefik.http.routers.map-storage-ssl.service=map-storage"
      - "traefik.http.routers.map-storage-ssl.tls=true"
      - "traefik.http.routers.map-storage-ssl.tls.certresolver=myresolver"

volumes:
  redisdata:
```
