### ISSUE TITLE
docker-compose.prod 

### ISSUE THREAD

**Issue by GregLebreton** [thecodingmachine/workadventure#2726]
Hi there! 
Great piece of software you working on here!

We are a french association to promote numeric culture and open source for people based in the XXth borough (www.legaragenumerique.fr).
In a partnership with the CNAM (conservatoire des arts et métiers) of Paris, we give classes of devops and we deployed an instance of workadventure to propose an alternative to other remote tools and show the possibilties of numeric development. 

We didn't managed to use your docker-compose.prod as it is to deploy it, but we managed we found a workaround putting a nginx proxy manager in front to manage the entrypoint to the stack.
We would love to make it work as it should be as the chat doens't work as it is (everything else OIDC included is working flawlessly).
If somebody could help us make it work in the state of the rules, it would be very gentle and help promote the tool for the new devops generation that is coming.

Thanks and keep the good work!

**Comment by LindezaGrey** [comment]
Hi there!
there are some issues with the whole new chat system that i encountered myself. lots of things aren`t really finished yet and not documented. (this should not be a criticism to the developers, they are doing a great job 😃 ) 
Could you show me the error logs from your containers and the compose file? i have some suspicions...

**Comment by GregLebreton** [comment]
Hi, thank you for the help, as I said, we have a home workaround that makes the containers communicates between them internally with /front, /chat, /uploader,... URLs.
The domain used is adventure.legaragenumerique.fr.

Here are the logs of the front:
```bash
front_1          | 2022/10/25 01:20:31 [error] 16#16: *6 open() "/usr/share/nginx/html/assets/index.adb76886.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.adb76886.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 01:20:31 [error] 16#16: *6 open() "/usr/share/nginx/html/assets/index.b5736735.css" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.b5736735.css HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 01:20:31 [error] 16#16: *6 open() "/usr/share/nginx/html/env-config.8c58b757cc2149dad7f88185d9519173.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /env-config.8c58b757cc2149dad7f88185d9519173.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 07:50:17 [error] 15#15: *25 open() "/usr/share/nginx/html/assets/index.adb76886.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.adb76886.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 07:50:17 [error] 15#15: *26 open() "/usr/share/nginx/html/assets/index.b5736735.css" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.b5736735.css HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 07:50:17 [error] 15#15: *26 open() "/usr/share/nginx/html/env-config.8c58b757cc2149dad7f88185d9519173.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /env-config.8c58b757cc2149dad7f88185d9519173.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 08:15:56 [error] 16#16: *28 open() "/usr/share/nginx/html/assets/index.b5736735.css" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.b5736735.css HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "http://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 08:15:56 [error] 16#16: *28 open() "/usr/share/nginx/html/assets/index.adb76886.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.adb76886.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "http://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 08:15:57 [error] 16#16: *29 open() "/usr/share/nginx/html/env-config.8c58b757cc2149dad7f88185d9519173.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /env-config.8c58b757cc2149dad7f88185d9519173.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "http://adventure.legaragenumerique.fr/chat"
front_1          | 2022/10/25 08:28:35 [error] 16#16: *33 open() "/usr/share/nginx/html/assets/index.adb76886.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.adb76886.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat/"
front_1          | 2022/10/25 08:28:35 [error] 16#16: *33 open() "/usr/share/nginx/html/assets/index.b5736735.css" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /assets/index.b5736735.css HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat/"
front_1          | 2022/10/25 08:28:35 [error] 16#16: *34 open() "/usr/share/nginx/html/env-config.8c58b757cc2149dad7f88185d9519173.js" failed (2: No such file or directory), client: 192.168.48.10, server: localhost, request: "GET /env-config.8c58b757cc2149dad7f88185d9519173.js HTTP/1.1", host: "adventure.legaragenumerique.fr", referrer: "https://adventure.legaragenumerique.fr/chat/"
```

Thanks again for your time, and yes, the devs make a great job here!

**Comment by LindezaGrey** [comment]
hmm, for your custom setup i would definitely need more information especially with the extra nginx. If setup correctly the traefik version should be enough. What seems wrong though is, that the "front" container is asked for the chat assets. You have an extra chat container right? Please make sure that on your front container the env-variable CHAT_URL is set. This is not in the example file "single domain" but you can find it documented here: https://github.com/thecodingmachine/workadventure/blob/develop/docker-compose.yaml
(there it is set on the play container, which is the front)

 Is there any chance of providing your compose file if this change does not work?

**Comment by GregLebreton** [comment]
Sure,
the nginx proxy is set to proxy every traffic form ports 80 and 443 to the traefik container (to his docker network IP and port 9999) and issues the ssl certificates.
As you can see, the traefik in compose listen on the 9999 port. I know it's a dirty workaround since the nginx proxy id doing part of the job that the traefik should do, but at least, it works that way...

```yaml
services:
  
  reverse-proxy:
    image: traefik:v2.5
    command:
      - --log.level=WARN
      - --providers.docker
      - --entryPoints.web.address=:80
    ports:
      - "9999:80"
    depends_on:
      - pusher
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  front:
    image: thecodingmachine/workadventure-front:master
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: $JITSI_URL
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      PUSHER_URL: /pusher
      ADMIN_URL: /back
      CHAT_URL: /chat
#      CHAT_URL: ${CHAT_HOST}
#      ICON_URL: ${ICON_HOST}
      ICON_URL: /icon
      TURN_SERVER: "${TURN_SERVER}"
      TURN_USER: "${TURN_USER}"
      TURN_PASSWORD: "${TURN_PASSWORD}"
      MAX_PER_GROUP: "${MAX_PER_GROUP}"
      MAX_USERNAME_LENGTH: "${MAX_USERNAME_LENGTH}"
      START_ROOM_URL: "${START_ROOM_URL}"
      DISABLE_NOTIFICATIONS: "${DISABLE_NOTIFICATIONS}"
      SKIP_RENDER_OPTIMIZATIONS: "${SKIP_RENDER_OPTIMIZATIONS}"
      ENABLE_OPENID: 1
      DISABLE_ANONYMOUS: ${DISABLE_ANONYMOUS}
      ENABLE_CHAT: ${ENABLE_CHAT} 
    labels:
      - "traefik.http.middlewares.strip-front-prefix.stripprefix.prefixes=/front"
      - "traefik.http.routers.front.rule=PathPrefix(`/`)"
      - "traefik.http.routers.front.entryPoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.routers.front.service=front"
    restart: unless-stopped
  
  pusher:
    image: thecodingmachine/workadventure-pusher:master
    environment:
      SECRET_JITSI_KEY: "${SECRET_JITSI_KEY}"
      SECRET_KEY: ${SECRET_KEY}
      API_URL: back:50051
      ADMIN_API_URL: "${ADMIN_API_URL}"
      ADMIN_API_TOKEN: "${ADMIN_API_TOKEN}"
      JITSI_URL: ${JITSI_URL}
      JITSI_ISS: ${JITSI_ISS}
      FRONT_URL : ${FRONT_URL}
      ENABLE_CHAT: ${ENABLE_CHAT}
      OPID_PROMPT: https://id.legaragenumerique.fr/oauth/realms/garagenum/protocol/openid-connect/auth
      OPID_CLIENT_ID: ${OPID_CLIENT_ID}
      OPID_CLIENT_SECRET: ${OPID_CLIENT_SECRET}
      OPID_CLIENT_ISSUER: ${OPID_CLIENT_ISSUER}
      OPID_CLIENT_REDIRECT_URL: ${OPID_CLIENT_REDIRECT_URL}
      OPID_PROFILE_SCREEN_PROVIDER: ${OPID_PROFILE_SCREEN_PROVIDER}
      DISABLE_ANONYMOUS: ${DISABLE_ANONYMOUS}
      OPID_USERNAME_CLAIM: ${OPID_USERNAME_CLAIM}
      EJABBERD_DOMAIN: ${EJABBERD_DOMAIN}
      EJABBERD_WS_URI: ${EJABBERD_WS_URI}
      START_ROOM_URL: "${START_ROOM_URL}"
#      CHAT_URL: ${CHAT_HOST}
      CHAT_URL: /chat
    labels:
      - "traefik.http.middlewares.strip-pusher-prefix.stripprefix.prefixes=/pusher"
      - "traefik.http.routers.pusher.rule=PathPrefix(`/pusher`)"
      - "traefik.http.routers.pusher.middlewares=strip-pusher-prefix@docker"
      - "traefik.http.routers.pusher.entryPoints=web"
      - "traefik.http.services.pusher.loadbalancer.server.port=8080"
      - "traefik.http.routers.pusher.service=pusher"
    restart: unless-stopped

  back:
    image: thecodingmachine/workadventure-back:master
    environment:
      SECRET_KEY: ${SECRET_KEY}
      STARTUP_COMMAND_1: yarn install
      SECRET_JITSI_KEY: "${SECRET_JITSI_KEY}"
      ADMIN_API_TOKEN: "${ADMIN_API_TOKEN}"
      ADMIN_API_URL: "${ADMIN_API_URL}"
      JITSI_URL: ${JITSI_URL}
      JITSI_ISS: ${JITSI_ISS}
      MAX_PER_GROUP: ${MAX_PER_GROUP}
      TURN_STATIC_AUTH_SECRET: "${TURN_STATIC_AUTH_SECRET}"
      REDIS_HOST: redis
      ENABLE_CHAT: ${ENABLE_CHAT}
      EJABBERD_API_URI: ${EJABBERD_API_URI} 
      EJABBERD_DOMAIN: ${EJABBERD_DOMAIN}
    labels:
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.back.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.back.middlewares=strip-api-prefix@docker"
      - "traefik.http.routers.back.entryPoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back.service=back"
    restart: unless-stopped

  uploader:
    image: thecodingmachine/workadventure-uploader:master
    environment:
      - UPLOADER_URL=//${UPLOADER_HOST}
      #REDIS
      - REDIS_HOST=${UPLOADER_REDIS_HOST}
      - REDIS_PORT=${UPLOADER_REDIS_PORT}
      #CHAT
      - ADMIN_API_URL=${ADMIN_API_URL}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    labels:
      - "traefik.http.middlewares.strip-uploader-prefix.stripprefix.prefixes=/uploader"
      - "traefik.http.routers.uploader.rule=PathPrefix(`/uploader`)"
      - "traefik.http.routers.uploader.middlewares=strip-uploader-prefix@docker"
      - "traefik.enable=true"
      - "traefik.http.routers.uploader.entryPoints=web"
      - "traefik.http.services.uploader.loadbalancer.server.port=8080"
      - "traefik.http.routers.uploader.service=uploader"

  chat:
    image: thecodingmachine/workadventure-chat:master
    environment:
      - FRONT_HOST_URL= /front
#      - FRONT_URL= ${FRONT_URL}
      - PUSHER_URL= /pusher
      - UPLOADER_URL= /uploader
      - ICON_URL=/icon
      - EJABBERD_DOMAIN=ejabberd
#      - EMBEDLY_KEY=${EMBEDLY_KEY}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD}
      - ENABLE_OPENID=1
    labels:
      - "traefik.http.middlewares.strip-chat-prefix.stripprefix.prefixes=/chat"
      - "traefik.http.routers.chat.rule=PathPrefix(`/chat`)"
      - "traefik.http.routers.chat.middlewares=strip-chat-prefix@docker"
      - "traefik.http.routers.chat.service=chat"
      - "traefik.http.routers.chat.entryPoints=web"
      - "traefik.http.services.chat.loadbalancer.server.port=80"

  icon:
    image: matthiasluedtke/iconserver:v3.13.0
    labels:
      - "traefik.http.middlewares.strip-icon-prefix.stripprefix.prefixes=/icon"
      - "traefik.http.routers.icon.rule=PathPrefix(`/icon`)"
      - "traefik.http.routers.icon.middlewares=strip-icon-prefix@docker"
      - "traefik.enable=true"
      - "traefik.http.routers.icon.entryPoints=web"
      - "traefik.http.services.icon.loadbalancer.server.port=8080"

  ejabberd:
    image: thecodingmachine/workadventure-simple-ecs:master

  redis:
    image: redis:6
    restart: unless-stopped

```

I didn't understood why the prod compose didn't get the job alone, traefik issued the ssl certificates properly but afterwards nothing works with the standard address (play.adventure.legaragenumerique.fr) and nothing in the logs.

**Comment by LindezaGrey** [comment]
i see, there are several things i would change. i could prepare a working compose file that is as close as possible to your setup. i would recommend to skip openid for the moment until everything works, and then implement it again. my preferred way would be to have subdomains for every container and not the path parameter.

so instead of adventure.legaragenumerique.fr/api, adventure.legaragenumerique.fr/front, adventure.legaragenumerique.fr/uploader, adventure.legaragenumerique.fr/chat
it would be api.adventure.legaragenumerique.fr, front.adventure.legaragenumerique.fr, etc...
This way we could eliminate several possible problems.

is that ok for you?

**Comment by GregLebreton** [comment]
I'm ok with that since it is to make it work.
I'm still trying to make the docker-compose.prod work on my side to see if I can get some helpful logs.
Thanks for your time and help!

**Comment by moufmouf** [comment]
Hey guys!

Just a quick heads-up.
Yesterday evening, we pushed a big refactoring to the "master" branch.
There is no more "front" and "pusher" containers but only one "play" container.

We are currently fixing bugs on the master branch right now. My advice would be to target directly a tagged version (the latest in the 1.12.x tags).

We need a few days to make the master branch rock-solid again. Meanwhile, the tagged versions are the way to go :D

**Comment by LindezaGrey** [comment]
yes, this is one of the changes i would have made ;) using generic tags is always a bad idea (like "latest", "develop" etc)
Looking forward to the big change. Thanks for the info

**Comment by LindezaGrey** [comment]
@GregLebreton i just finished a compose file and tested it on a fresh server. basically the only thing that you need ist a valid DNS setup and a server. so in your case you could have an A entry which points *.adventure.legaragenumerique.fr to your docker host IP.


i removed all env vars to make it very explicit and ready for copy paste. i tried to fill in your details already. there are some "changme" comments in the code.
furthermore you need one config file for the ejabberd service.

```yml
version: "3.8"

services:
  
  reverse-proxy:
    image: traefik:v2.5.6
    container_name: adventure_traefik
    <<: *restart
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=false"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      #change me
      - "--certificatesResolvers.le.acme.email=you@you.fr"
      - "--certificatesResolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      - "443:443"
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme
    networks:
      adventure_net:

  front:
    image: thecodingmachine/workadventure-front:v1.12.10
    environment:
      DEBUG_MODE: "false"
      JITSI_URL: "meet.jit.si"
      JITSI_PRIVATE_MODE: "false"
      PUSHER_URL: https://pusher.adventure.legaragenumerique.fr
      CHAT_URL: https://chat.adventure.legaragenumerique.fr
      ICON_URL: https://icon.adventure.legaragenumerique.fr
      # needs a coturn container
      TURN_SERVER: turn:turn.adventure.legaragenumerique.fr:3478?transport=tcp
      TURN_USER: workadventure
      TURN_PASSWORD: WorkAdventure123
      MAX_PER_GROUP: 4
      MAX_USERNAME_LENGTH: 15
      START_ROOM_URL: /_/global/thecodingmachine.github.io/workadventure-map-starter-kit/map.json
      # DISABLE_NOTIFICATIONS: "${DISABLE_NOTIFICATIONS}"
      # SKIP_RENDER_OPTIMIZATIONS: "${SKIP_RENDER_OPTIMIZATIONS}"
      # ENABLE_OPENID: 1
      # DISABLE_ANONYMOUS: ${DISABLE_ANONYMOUS}
      ENABLE_CHAT: "true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-front.rule=Host(`play.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-front.entryPoints=web
      - traefik.http.services.adventure-front.loadbalancer.server.port=80
      - traefik.http.routers.adventure-front.middlewares=https_redirect

      - traefik.http.routers.adventure-front-ssl.rule=Host(`play.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-front-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-front-ssl.tls=true
      - traefik.http.routers.adventure-front-ssl.service=adventure-front
      - traefik.http.routers.adventure-front-ssl.tls.certresolver=le
      - traefik.http.routers.adventure-front-ssl.middlewares=redir
      # middlewares
      - traefik.http.middlewares.redir.redirectregex.regex=^https://www\.(.+)
      - traefik.http.middlewares.redir.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.redir.redirectregex.permanent=true
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
    restart: unless-stopped
    networks:
      adventure_net:

  pusher:
    image: thecodingmachine/workadventure-pusher:v1.12.10
    environment:
      # SECRET_JITSI_KEY: "${SECRET_JITSI_KEY}"
      SECRET_KEY: yourSecretKey
      API_URL: back:50051
      # ADMIN_API_URL: "${ADMIN_API_URL}"
      # ADMIN_API_TOKEN: "${ADMIN_API_TOKEN}"
      JITSI_URL: meet.jit.si
      # JITSI_ISS: ${JITSI_ISS}
      FRONT_URL : https://play.adventure.legaragenumerique.fr
      ENABLE_CHAT: "true"
      # this should be "login" anyway
      # OPID_PROMPT: https://id.legaragenumerique.fr/oauth/realms/garagenum/protocol/openid-connect/auth
      # OPID_CLIENT_ID: ${OPID_CLIENT_ID}
      # OPID_CLIENT_SECRET: ${OPID_CLIENT_SECRET}
      # OPID_CLIENT_ISSUER: ${OPID_CLIENT_ISSUER}
      # OPID_CLIENT_REDIRECT_URL: ${OPID_CLIENT_REDIRECT_URL}
      # OPID_PROFILE_SCREEN_PROVIDER: ${OPID_PROFILE_SCREEN_PROVIDER}
      DISABLE_ANONYMOUS: "false"
      # OPID_USERNAME_CLAIM: ${OPID_USERNAME_CLAIM}
      EJABBERD_API_URI: http://ejabberd:5443/api
      EJABBERD_DOMAIN: ejabberd
      EJABBERD_WS_URI: ws://ejabberd:5443/ws
      EJABBERD_JWT_SECRET: mySecretJwtToken
      START_ROOM_URL: /_/global/thecodingmachine.github.io/workadventure-map-starter-kit/map.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-pusher.rule=Host(`pusher.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-pusher.entryPoints=web
      - traefik.http.services.adventure-pusher.loadbalancer.server.port=8080
      - traefik.http.routers.adventure-pusher-ssl.rule=Host(`pusher.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-pusher-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-pusher-ssl.tls=true
      - traefik.http.routers.adventure-pusher-ssl.service=adventure-pusher
      - traefik.http.routers.adventure-pusher-ssl.tls.certresolver=le
    restart: unless-stopped
    networks:
      adventure_net:

  back:
    image: thecodingmachine/workadventure-back:v1.12.10
    command: yarn run runprod
    environment:
      # SECRET_KEY: ${SECRET_KEY}
      # SECRET_JITSI_KEY: "${SECRET_JITSI_KEY}"
      ADMIN_API_TOKEN: "${ADMIN_API_TOKEN}"
      ADMIN_API_URL: "${ADMIN_API_URL}"
      JITSI_URL: "meet.jit.si"
      JITSI_ISS: ""
      MAX_PER_GROUP: 4
      # TURN_STATIC_AUTH_SECRET: "${TURN_STATIC_AUTH_SECRET}"
      REDIS_HOST: redis
      ENABLE_CHAT: "true"
      EJABBERD_API_URI: http://ejabberd:5443/api
      EJABBERD_DOMAIN: //xmpp.adventure.legaragenumerique.fr
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-back.rule=Host(`api.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-back.entryPoints=web
      - traefik.http.services.adventure-back.loadbalancer.server.port=8080
      - traefik.http.routers.adventure-back-ssl.rule=Host(`api.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-back-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-back-ssl.tls=true
      - traefik.http.routers.adventure-back-ssl.service=adventure-back
      - traefik.http.routers.adventure-back-ssl.tls.certresolver=le
    restart: unless-stopped
    networks:
      adventure_net:

# wont work for now
  uploader:
    image: thecodingmachine/workadventure-uploader:v1.12.10
    environment:
      UPLOADER_URL: //uploader
      #REDIS
      REDIS_HOST: redis
      REDIS_PORT: 6379
      UPLOADER_REDIS_DB_NUMBER: 0
      #CHAT
      ADMIN_API_URL: 
      ENABLE_CHAT_UPLOAD: "false"
      UPLOAD_MAX_FILESIZE: 10485760
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-uploader.rule=Host(`uploader.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-uploader.entryPoints=web
      - traefik.http.services.adventure-uploader.loadbalancer.server.port=8080
      - traefik.http.routers.adventure-uploader-ssl.rule=Host(`uploader.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-uploader-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-uploader-ssl.service=adventure-uploader
      - traefik.http.routers.adventure-uploader-ssl.tls=true
      - traefik.http.routers.adventure-uploader-ssl.tls.certresolver=le
    networks:
      adventure_net:

  chat:
    image: thecodingmachine/workadventure-chat:v1.12.10
    environment:
      PUSHER_URL: //pusher.adventure.legaragenumerique.fr
      UPLOADER_URL: //uploader.adventure.legaragenumerique.fr
      # EMBEDLY_KEY: ${EMBEDLY_KEY}
      ENABLE_CHAT_UPLOAD: "false"
      EJABBERD_DOMAIN: //xmpp.adventure.legaragenumerique.fr
      # ENABLE_OPENID: $OPID_CLIENT_ID

    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-chat.rule=Host(`chat.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-chat.entryPoints=web
      - traefik.http.services.adventure-chat.loadbalancer.server.port=80
      - traefik.http.routers.adventure-chat-ssl.rule=Host(`chat.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-chat-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-chat-ssl.service=adventure-chat
      - traefik.http.routers.adventure-chat-ssl.tls=true
      - traefik.http.routers.adventure-chat-ssl.tls.certresolver=le
    networks:
      adventure_net:

  icon:
    image: matthiasluedtke/iconserver:v3.13.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.adventure-icon.rule=Host(`icon.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-icon.entryPoints=web,traefik
      - traefik.http.services.adventure-icon.loadbalancer.server.port=8080
      - traefik.http.routers.adventure-icon-ssl.rule=Host(`icon.adventure.legaragenumerique.fr`)
      - traefik.http.routers.adventure-icon-ssl.entryPoints=websecure
      - traefik.http.routers.adventure-icon-ssl.tls=true
      - traefik.http.routers.adventure-icon-ssl.service=adventure-icon
      - traefik.http.routers.adventure-icon-ssl.tls.certresolver=le
    networks:
      adventure_net:

  ejabberd:
    container_name: adventure-ejabberd
    image: ghcr.io/processone/ejabberd:22.05
    <<: *restart
    networks:
      adventure_net:
    volumes:
      - ./ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.xmpp.rule=Host(`xmpp.adventure.legaragenumerique.fr`)
      - traefik.http.routers.xmpp.entryPoints=web
      - traefik.http.services.xmpp.loadbalancer.server.port=5380
      - traefik.http.routers.xmpp-ssl.rule=Host(`xmpp.adventure.legaragenumerique.fr`)
      - traefik.http.routers.xmpp-ssl.entryPoints=websecure
      - traefik.http.routers.xmpp-ssl.tls=true
      - traefik.http.routers.xmpp-ssl.service=xmpp


  redis:
    container_name: adventure-redis
    image: redis:6
    volumes:
      - redisdata:/data
    networks:
      adventure_net:


  coturn:
    image: coturn/coturn:4.5.2
    <<: *restart
    command:
      - turnserver
      #- -c=/etc/coturn/turnserver.conf
      - --log-file=stdout

      # change me
      - --external-ip=217.70.188.81
      - --realm=turn.adventure.legaragenumerique.fr
      - --server-name=turn.adventure.legaragenumerique.fr

      - --listening-port=3478
      - --min-port=10002
      - --max-port=10100
      - --tls-listening-port=5349
      - --listening-ip=0.0.0.0
      - --lt-cred-mech
      # Enable Coturn REST API to validate temporary passwords.
      #- --use-auth-secret
      #- --static-auth-secret=SomeStaticAuthSecret
      #- --userdb=/var/lib/turn/turndb
      - --user=workadventure:WorkAdventure123
      # use real-valid certificate/privatekey files
      #- --cert=/root/letsencrypt/fullchain.pem
      #- --pkey=/root/letsencrypt/privkey.pem
    network_mode: host


networks:
  adventure_net:

volumes:
  acme:
  redisdata:

```
Place the attached config file (change from .txt to yml, github does not allow uploads...) in the same directory as the docker-compose.ym file
[ejabberd.txt](https://github.com/thecodingmachine/workadventure/files/9862187/ejabberd.txt)

This should also make traefik generate your certificates and store them in a volume. This was absent in your config. I also enabled the debug interface of traefik which is on port 8082 so you have a nice GUI about all your routes.

Please note that i also added a turn server, so make sure the ports are available on your machine. This is used as fallback if p2p connections cannot be made directly with workadventure.

This is the screenshot of the working office with the above config ;)
![image](https://user-images.githubusercontent.com/39629455/197830846-882648e3-fab4-4a62-a2fb-101689b83868.png)


i hope this works for you
