### ISSUE TITLE
ejabberd container fails to start

### ISSUE THREAD

**Issue by ainulhamdani** [thecodingmachine/workadventure#3030]
I am using env and yaml file in the contrib folder, everyhing is running fine except the ejabberd container.
The error i get is :
`workadventure-ejabberd-1       | envsubst: error while reading "standard input": Is a directory`
`workadventure-ejabberd-1 exited with code 1`

**Comment by ainulhamdani** [comment]
So, after several tests, I noticed that when I run the docker compose, it will create **xmpp/ejabberd.template.yml**, but when i checked, **ejabberd.template.yml** was a folder not a file. When I changed it to a file and run docker compose again, I get different error:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/office/xmpp/ejabberd.template.yml" to rootfs at "/opt/ejabberd/conf/ejabberd.template.yml": mount /root/office/xmpp/ejabberd.template.yml:/opt/ejabberd/conf/ejabberd.template.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

Any insight on this?

**Comment by erwinpalma** [comment]
Hi, I had the same issue, and I changed the path from `../../xmpp/...` to `./xmpp/...`

```yaml
ejabberd:
    image: workadventure/ejabberd:v1
    ports:
      - '5443:5443'
    environment:
      - CTL_ON_CREATE=register ${EJABBERD_USER} ${EJABBERD_DOMAIN} ${EJABBERD_PASSWORD}
      - JWT_SECRET=${EJABBERD_JWT_SECRET}
      - EJABBERD_DOMAIN=${EJABBERD_DOMAIN}
      - EJABBERD_USER=${EJABBERD_USER}
      - EJABBERD_PASSWORD=${EJABBERD_PASSWORD}
    volumes:
      # - ../../xmpp/ejabberd.template.yml:/opt/ejabberd/conf/ejabberd.template.yml
      - ./xmpp/ejabberd.template.yml:/opt/ejabberd/conf/ejabberd.template.yml
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.strip-ejabberd-prefix.stripprefix.prefixes: "/xmpp"
      traefik.http.routers.ejabberd.middlewares: "strip-ejabberd-prefix@docker"
      traefik.http.routers.ejabberd.rule: "Host(`${DOMAIN}`) && PathPrefix(`/xmpp`)"
      traefik.http.routers.ejabberd.entryPoints: "web"
      traefik.http.services.ejabberd.loadbalancer.server.port: "5443"
      traefik.http.routers.ejabberd-ssl.middlewares: "strip-ejabberd-prefix@docker"
      traefik.http.routers.ejabberd-ssl.rule: "Host(`${DOMAIN}`) && PathPrefix(`/xmpp`)"
      traefik.http.routers.ejabberd-ssl.entryPoints: "websecure"
      traefik.http.routers.ejabberd-ssl.service: "ejabberd"
      traefik.http.routers.ejabberd-ssl.tls: "true"
      traefik.http.routers.ejabberd-ssl.tls.certresolver: "myresolver"
    restart: ${RESTART_POLICY}

```

And it Works for me, but if I move my docker-compose* file to other location, O got the same issue :(
