### ISSUE TITLE
back server crashes because of missing variable for ADMIN_API_URL

### ISSUE THREAD

**Issue by nextgen-networks** [thecodingmachine/workadventure#3099]
I get a crashing WA when utilizing "docker-compose.prod.yaml" and ".env.prod.template" from current master tree.

**Here is the output for "sudo docker container ls --all":**

`CONTAINER ID   IMAGE                                               COMMAND                  CREATED         STATUS                          PORTS                                                                                              NAMES
5644dba778e6   thecodingmachine/workadventure-back:master          "docker-entrypoint.s…"   4 minutes ago   Restarting (1) 37 seconds ago  `

**Here is the output for: "sudo docker logs workadventure_back_1":**

> workadventureback@1.0.0 runprod
> ts-node --transpileOnly ./server.ts

-----------------------------------------
FATAL ERRORS FOUND IN ENVIRONMENT VARIABLES!!!
-----------------------------------------

For variable "ADMIN_API_URL": Invalid url

-----------------------------------------

npm ERR! Lifecycle script `runprod` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: workadventureback@1.0.0
npm ERR!   at location: /usr/src/back
npm notice
npm notice New major version of npm available! 8.19.2 -> 9.5.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.5.1>
npm notice Run `npm install -g npm@9.5.1` to update!
npm notice

Am I the only one with that behavior? ;-)
Any helpful ideas to solve are appreciated.

Thanks!

**Comment by LindezaGrey** [comment]
There was a recent change https://github.com/thecodingmachine/workadventure/commit/7b3f69cc9365f6b16e25523dbb750db18451a5cd

Regarding this environment variable. Did you change the value of the variable? If not maybe you can try to explicitly set it to an empty string.

**Comment by nextgen-networks** [comment]
> Regarding this environment variable. Did you change the value of the variable? If not maybe you can try to explicitly set it to an empty string.

No, I did not change the value.
It is empty in the ".env.prod.template" file that I used.
Also no change when setting it to an empty string via 
ADMIN_API_URL=""
or
ADMIN_API_URL=''

**Comment by LindezaGrey** [comment]
i see. can you comment out the ADMIN_API_URL env. variable in your docker-compose?

```
back:
    image: thecodingmachine/workadventure-back:${VERSION}
    environment:
      - PLAY_URL=https://${PLAY_HOST}
      - SECRET_JITSI_KEY
      - ENABLE_FEATURE_MAP_EDITOR
      - SECRET_KEY
      - ADMIN_API_TOKEN
      - ADMIN_API_URL
...
```

to;

```yml
back:
    image: thecodingmachine/workadventure-back:${VERSION}
    environment:
      - PLAY_URL=https://${PLAY_HOST}
      - SECRET_JITSI_KEY
      - ENABLE_FEATURE_MAP_EDITOR
      - SECRET_KEY
      # - ADMIN_API_TOKEN
      # - ADMIN_API_URL
...
```

I just tested it and it resolved the error
