### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by christianreiss** [thecodingmachine/workadventure#452]
Hey folks,

I am running the current git repo, edited the docker-compose file and launched via docker-compose up. After a while all the containers were online but every join / create a map is aborted with a "404 - File not Found" error.

Here is my docker-compose file:

```
version: "3"
services:
  reverse-proxy:
    image: traefik:v2.0
    command:
      - --api.insecure=true
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    depends_on:
      - back
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  front:
    image: thecodingmachine/nodejs:14
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: $JITSI_URL
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: development
      API_URL: api.example.com
      ADMIN_URL: admin.example.com
      STARTUP_COMMAND_1: yarn install
      TURN_SERVER: "turn:coturn.workadventu.re:443,turns:coturn.workadventu.re:443"
      TURN_USER: workadventure
      TURN_PASSWORD: WorkAdventure123
    command: yarn run start
    volumes:
      - ./front:/usr/src/app
    labels:
      - "traefik.http.routers.front.rule=Host(`play.example.com`)"
      - "traefik.http.routers.front.entryPoints=web,traefik"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front-ssl.rule=Host(`play.example.com`)"
      - "traefik.http.routers.front-ssl.entryPoints=websecure"
      - "traefik.http.routers.front-ssl.tls=true"
      - "traefik.http.routers.front-ssl.service=front"

  maps:
    image: thecodingmachine/nodejs:12-apache
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: development
      #APACHE_DOCUMENT_ROOT: dist/
      #APACHE_EXTENSIONS: headers
      #APACHE_EXTENSION_HEADERS: 1
      STARTUP_COMMAND_0: sudo a2enmod headers
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run dev &
    volumes:
      - ./maps:/var/www/html
    labels:
      - "traefik.http.routers.maps.rule=Host(`maps.example.com`)"
      - "traefik.http.routers.maps.entryPoints=web,traefik"
      - "traefik.http.services.maps.loadbalancer.server.port=80"
      - "traefik.http.routers.maps-ssl.rule=Host(`maps.example.com`)"
      - "traefik.http.routers.maps-ssl.entryPoints=websecure"
      - "traefik.http.routers.maps-ssl.tls=true"
      - "traefik.http.routers.maps-ssl.service=maps"

  back:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run profile
    environment:
      STARTUP_COMMAND_1: yarn install
      SECRET_KEY: yourSecretKey
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ALLOW_ARTILLERY: "true"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./back:/usr/src/app
    labels:
      - "traefik.http.routers.back.rule=Host(`api.example.com`)"
      - "traefik.http.routers.back.entryPoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back-ssl.rule=Host(`api.example.com`)"
      - "traefik.http.routers.back-ssl.entryPoints=websecure"
      - "traefik.http.routers.back-ssl.tls=true"
      - "traefik.http.routers.back-ssl.service=back"


  website:
    image: thecodingmachine/nodejs:12-apache
    environment:
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: npm run watch &
      APACHE_DOCUMENT_ROOT: dist/
    volumes:
      - ./website:/var/www/html
    labels:
      - "traefik.http.routers.website.rule=Host(`example.com`)"
      - "traefik.http.routers.website.entryPoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=80"
      - "traefik.http.routers.website-ssl.rule=Host(`example.com`)"
      - "traefik.http.routers.website-ssl.entryPoints=websecure"
      - "traefik.http.routers.website-ssl.tls=true"
      - "traefik.http.routers.website-ssl.service=website"

  messages:
    image: thecodingmachine/workadventure-back-base:latest
    environment:
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run proto:watch
    volumes:
      - ./messages:/usr/src/app
      - ./back:/usr/src/back
      - ./front:/usr/src/front
```

I replaced all the domains with example.com, but the real deal has alll the a-records and cname for things like api. and maps. going.
I simply copied the .env.template to .env, but did not change anything inside it.

What am I missing here?
Thanks :)

**Comment by moufmouf** [comment]
Hey @christianreiss ,

Good question.
We have a small bug currently. The error page can display "404 not found", but actually, the error can be a HTTP 500 or a certificate problem, or whatever...

Could you open your developers tools, go to the Network tab, and have a look at requests performed?
Check if one request goes in a HTTP status > 400, and let me know what you find. That will help us pinpoint the issue.

**Comment by christianreiss** [comment]
Hey there,

thanks for your reply. Seems non are 4x or 5x. I do get an invalid cert when trying to access via https. And during that I get CORS errors using traefik. Are there any instructions on deploying CORS nginx headers and letsencrypt?

Cheers,
-Chris.

**Comment by moufmouf** [comment]
Ok, it's not an issue with CORS, it's clearly an issue with certificates.
You need to fix those certificates to be able to use WorkAdventure.

If you want to test in your browser, there is a workaround:

Simply browse to each domain name once, and accept the security exception in your browser.

So in your sample case, browse to:

- example.com
- api.example.com
- play.example.com
- maps.example.com

**Comment by christianreiss** [comment]
Is there a way to letsencrypt all this?

**Comment by christianreiss** [comment]
Update: That works; just need real life certs now.

**Comment by moufmouf** [comment]
Note: you can indeed use Let's Encrypt with Traefik to automatically get certificates.

**Comment by christianreiss** [comment]
All is fixed; 404 means certificate error in this case. After rolling out letsencrypt with the dockerfile all is well without any cert wooziness. Thanks!

**Comment by mmatiaschek** [comment]
@christianreiss can you please share your docker-compose.yaml for letsencrypt?

**Comment by benlooning** [comment]
> @christianreiss can you please share your docker-compose.yaml for letsencrypt?

@mmatiaschek here you go:
```
version: "3"
services:
  reverse-proxy:
    image: traefik:v2.0
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=admin@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    depends_on:
      - back
      - front
    volumes:
      - /var/docker/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
...
```
Replace "admin@example.com" with your own email and make sure to create a corresponding acme.json file:
```
sudo mkdir -p /var/docker/letsencrypt
sudo touch /var/docker/letsencrypt/acme.json
sudo chmod 600 /var/docker/letsencrypt/acme.json
```

and for every service (front, pusher, maps, back, uploader, website) you have to add the following label:
```
- "traefik.http.routers.<service>.tls.certresolver=myresolver"
```

For example (replace $HOST_NAME with your domain or set the corresponding environment variable in .env):
```
  website:
    image: thecodingmachine/nodejs:12-apache
    environment:
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: npm run watch &
      APACHE_DOCUMENT_ROOT: dist/
    volumes:
      - ./website:/var/www/html
    labels:
      - "traefik.http.routers.website.rule=Host(`$HOST_NAME`)"
      - "traefik.http.routers.website.entryPoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=80"
      - "traefik.http.routers.website-ssl.rule=Host(`$HOST_NAME`)"
      - "traefik.http.routers.website-ssl.entryPoints=websecure"
      - "traefik.http.routers.website-ssl.tls=true"
      - "traefik.http.routers.website-ssl.service=website"
      - "traefik.http.routers.website.tls.certresolver=myresolver"
```
