### ISSUE TITLE
SSL level

### ISSUE THREAD

**Issue by t10r** [thecodingmachine/workadventure#765]
Hi,

the workadventure maps have only a B ssl-level at ssllabs (https://www.ssllabs.com/ssltest/analyze.html?d=play.workadventu.re&hideResults=on). In my company this prevents access to the service.

It would be nice if the setup could get an A, this should work.

**Comment by nivadis** [comment]
could be done in traefik by adding additional ssl/tls config:
````
command:
      - --providers.file.directory=/configs/
volumes:
      - ./traefik.yaml:/configs/traefik_tls.yml
````

traefik.yaml:
````
tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  ````
